eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
server:
  port: 8764
spring:
  application:
    name: eurekaclient
    zipkin:
        base-url: http://localhost:9411
    sleuth:
        sampler:
            percentage: 1.0
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false
