eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
server:
  port: 8764
spring:
  application:
    name: eurekaclient
    zipkin:
      #指定 zipkinServer 的地址
      base-url: http://localhost:9411
    sleuth:
      sampler:
        #指定采样请求的百分比（默认为0.1，即10%）
        percentage: 1.0
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false
